import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

import { TanstackQueryProviders } from "@/components/provider/tanstack-query-provider";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={cn(
            nunito.className,
            "antialiased min-h-screen"
          )}
        >
          <TanstackQueryProviders>
            {children}
          </TanstackQueryProviders>
        </body>
    </html>
  );
}
